Changes in README.md
sadikkuzu/squiral pull request #3
Opened 2021-04-01 17:43 UTC by nikitamahoviya

Fixes #1  and Fixes #2 

I have made changes in the README file which suited the best, may you suggest me any more further changes.

2021-04-11 16:01 UTC, sadikkuzu commented
Thank you so much for your first contribution! 
Without people like you submitting PRs, open source projects couldn't be run. 
You rock, @nikitamahoviya! :rocket:

2021-04-11 16:05 UTC, sadikkuzu requested changes
I've added my review as inline comments.
Thanks again.

2021-04-11 16:05 UTC, sadikkuzu commented on README.md
> +![PyPI](https://img.shields.io/pypi/v/pip) [![made-with-python](https://img.shields.io/badge/Made%20with-Python-1f425f.svg)](https://www.python.org/) [![PyPI pyversions](https://img.shields.io/pypi/p
Actually, this project doesn't support Python 2.7.
We can get data directly from pypi, like those badges:
[ ![ ] ( https://img.shields.io/pypi/v/squiral )] (https://pypi.org/project/squiral/) 
[ ![ ] ( https://img.shields.io/pypi/pyversions/squiral.svg )] (https://pypi.org/project/squiral/)

2021-04-11 16:05 UTC, sadikkuzu commented on README.md
> +# Squiral
I prefer title as lowercase. (squiral)

2021-04-11 16:05 UTC, sadikkuzu commented on README.md
> +**Squ**are sp**iral**
I prefer header as lowercase. (square spiral)

2021-04-11 16:05 UTC, sadikkuzu commented on README.md
> +The basic idea behind printing this matrix is to start from the middle of the matrix and then moving
Cool description. Thanks a lot! ✨

2021-04-17 05:24 UTC, nikitamahoviya commented
> Thank you so much for your first contribution!
> Without people like you submitting PRs, open source projects couldn't be run.
> You rock, @nikitamahoviya!

Thank you so much for the appreciation, would love to contribute more!!

2021-07-04 00:13 UTC, sadikkuzu commented
Will be closed because PR#4 covers this changes.

2021-07-04 00:13 UTC, closed without merging