Changed the badges and case.
sadikkuzu/squiral pull request #4
Opened 2021-04-17 05:21 UTC by nikitamahoviya

2021-05-16 11:49 UTC, sadikkuzu commented
Thanks again for your contribution! 
Without people like you submitting PRs, open source projects couldn't be run.
You rock, @nikitamahoviya! 🚀

2021-05-16 11:50 UTC, sadikkuzu commented on README.md
> +![](https://img.shields.io/pypi/v/squiral) [![made-with-python](https://img.shields.io/badge/Made%20with-Python-1f425f.svg)](https://www.python.org/) ![]( https://img.shields.io/pypi/pyversions/squir
Very well done!

2021-05-16 11:50 UTC, sadikkuzu commented on pyproject.toml
> -version = "0.1.1"
Well, it's already been 0.1.2
https://github.com/sadikkuzu/squiral/blob/main/pyproject.toml#L3

2021-05-16 11:50 UTC, sadikkuzu commented on squiral/__init__.py
> -__version__ = '0.1.1'
Well, it's already been 0.1.2
https://github.com/sadikkuzu/squiral/blob/main/squiral/__init__.py#L1

2021-05-16 11:51 UTC, sadikkuzu commented on tests/test_squiral.py
> -    assert __version__ == '0.1.1'
Well, it's already been 0.1.2
https://github.com/sadikkuzu/squiral/blob/main/tests/test_squiral.py#L8

2021-05-16 11:51 UTC, sadikkuzu requested changes
I've added my review as inline comments.
I guess your PR is based on one of previous commits.
Thanks again.

2021-07-04 00:10 UTC, merged

2021-07-04 00:10 UTC, sadikkuzu commented
Thanks again @nikitamahoviya ✨

2021-07-04 05:55 UTC, nikitamahoviya commented
> Thanks again @nikitamahoviya ✨

Hey!!
Thank you so much😃
I am sorry I couldn't look into it once again as I just got engaged in my GSoC project.
It was a great experience working with you!!